version: 2
jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: v2-dependencies-{{ checksum "pnpm-lock.yaml" }}
      - run: npm install -g pnpm@7.33.7
      - run: pnpm config set store-dir ~/.pnpm-store
      - run: pnpm install --frozen-lockfile
      - save_cache:
          key: v2-dependencies-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ~/.pnpm-store
            - ./node_modules
      - run: pnpm test
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: v2-dependencies-{{ checksum "pnpm-lock.yaml" }}
      - run: npm install -g pnpm@7.33.7
      - run: pnpm config set store-dir ~/.pnpm-store
      - run: pnpm install --frozen-lockfile
      - save_cache:
          key: v2-dependencies-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ~/.pnpm-store
            - ./node_modules
      - run: pnpm build

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build
